package rfid.example.RFID.model;

public enum SessionStatus {
    OPEN,
    CLOSED,
    AUTO_CLOSED, // Retained for backward compatibility; no longer generated by new logic
    ABSENT       // Set by nightly job when employee forgot to check out
}
